### PR TITLE
Configure kube-{scheduler/controller-manager} leader elections

### PR DESCRIPTION
**Pull request by robdaemon**
Adds the leader-election flag to kube-scheduler (was already present on
kube-controller-manager)

Also sets the apiserver-count on kube-apiserver

### CODE REVIEW

**Comment by robdaemon** [comment]
**do not merge yet** - opening for feedback, since I'm still learning Salt :)

I'm not sure if this would trigger an update when other kube-master nodes are added? I'm going to need some help in testing that.

**Comment by inercia** [comment]
@robdaemon Could we have some context on this? Why are these flags needed?

**Comment by kiall** [comment]
@robdaemon Yes, this should trigger an update when changes are made to the cluster. Though I'd want to check that kubic's use of salt is the same as what I have in my head :)

@inercia https://kubernetes.io/docs/admin/high-availability/ - explains the leader election flag better than I could - "Master elected components" section. For the apiserver-count flag, it's (for whatever reason) not documented on the kubernetes HA page, but it's also essential for running more than 1 kube-apiserver process - https://github.com/kubernetes/kubernetes/issues/24327

Both changes are harmless when there is only 1 master, and required when there is more than 1 - @robdaemon  we should probably target this PR to the `master` rather than `ha` branch?

**Comment by inercia** [comment]
> Yes, this should trigger an update when changes are made to the cluster. Though I'd want to check that kubic's use of salt is the same as what I have in my head, i.e. they they highstate all machines cluster changes, or just the one being change? I assume all, but it's worth checking :)

AFAIK we currently _cannot change the cluster dynamically_, so new machines cannot be added right now... I think that is in our roadmap, but it would require some changes (new machines would have to be shown in the UI, they would have to be accepted, a role assigned, re-orchestrate, etc...)

**Comment by robdaemon** [comment]
@kiall I can retarget this PR. I was erring on the side of staying off master :)

**Comment by robdaemon** [comment]
Verified that this works as expected -

* apiserver-count is 2 when two master nodes are selected
* locks on kube-scheduler and kube-controller-manager are properly held in etcd, and when kube-scheduler or controller-manager are stopped on one node, the lock is released and the other node takes over

This is ready to go.

**Pull request merged**
