### PR TITLE
Do not assume minion_id is hostname/fqdn

### PR DESCRIPTION
**Pull request by ereslibre**

### CODE REVIEW

**Comment by robdaemon** [comment]
Something isn't right, this is outputting the wrong value to the `/etc/kubernetes/kubelet` file.

```
Apr 18 21:20:39 minion0 hyperkube[2684]: E0418 21:20:39.120421    2684 event.go:208] Unable to write event: 'Post https://fqdn:6443/api/v1/namespaces/default/events: dial tcp: lookup fqdn on 10.17.3.1:53: no such host' (may retry after sleeping)
```

And the `/etc/kubernetes/kubelet`:

```
# location of the api-server
KUBELET_API_SERVER="--api-servers=https://fqdn:6443"
```

**Comment by robdaemon** [comment]
That being said, the `/etc/sysconfig/etcd` file is correct on my master node.

**Comment by ereslibre** [comment]
Yes, I added [WIP] tag because we need to mine the fqdn, and use the mine. There's no way to get the fqdn grain for a specific node from the jinja template.

**Comment by ereslibre** [comment]
Everything should be fine now. I took advantage of the changes to refactor the pillar a bit, so we don't repeat ourselves too much.

**Pull request merged**
