### PR TITLE
[k8s 1.13][bsc#1122783] update critical pod configuration

### PR DESCRIPTION
**Pull request by MaximilianMeister**
https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/

bsc#1122783

Signed-off-by: Maximilian Meister <mmeister@suse.de>

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
related https://github.com/kubic-project/caasp-container-manifests/pull/212

**Comment by MaximilianMeister** [comment]
This can only be merged when we updated to kubernetes 1.11

**Comment by ereslibre** [comment]
Needs a rebase on top of #710 for passing salt.tests.

**Comment by ereslibre** [comment]
We would have to check, but the previous annotation wasn't actually used, and I'm not sure about the new annotation. I saw sometimes ago that these patches were necessary:

- https://github.com/kubic-project/salt/pull/681
- https://github.com/kubic-project/salt/pull/682

Since `ExperimentalCriticalPodAnnotation` is `false` by default as per https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/.

**Comment by MaximilianMeister** [comment]
> We would have to check, but the previous annotation wasn't actually used, and I'm not sure about the new annotation. I saw sometimes ago that these patches were necessary:
> 
> * #681
> * #682
> 
> Since `ExperimentalCriticalPodAnnotation` is `false` by default as per https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/.

good catch. this seems very likely. i think the best for now is to get those PR's merged

**Comment by MaximilianMeister** [comment]
now that we are on 1.13 we need to consider this

**Comment by lcavajani** [comment]
@MaximilianMeister `kube-flannel` pods would also require this annotation

**Comment by MaximilianMeister** [comment]
> `kube-flannel` pods would also require this annotation

@lcavajani thanks for the hint. updated

**Pull request merged**
