### PR TITLE
[WIP] Replace the bash script to deploy kube-dns with salt script

### PR DESCRIPTION
**Pull request by at1012**

### CODE REVIEW

**Comment by at1012** [comment]
@flavio @kiall I figured this out with Nikhil's help. The problem was that the sync wasn't happening because it's a readonly file system.  We made it read-write and copied the kubernetes state and the module files. It now seems to be working.

**Comment by at1012** [comment]
@flavio @kiall I figured this out with Nikhil's help. The problem was that the sync wasn't happening because it's a readonly file system.  We made it read-write and copied the kubernetes state and the module files. It now seems to be working.

**Comment by inercia** [comment]
Is this related to @flavio 's PR saltstack/salt#39514 ?

**Comment by at1012** [comment]
yup.

**Comment by inercia** [comment]
@at1012 what the status of this PR?

**Comment by flavio** [comment]
@SlickNik we would like to merge it, can someone from your team fix the conflicts and give it another round of tests?

**Comment by SlickNik** [comment]
Hi @flavio @inercia  -- I'm adding a ticket for it to our current sprint so we can resolve conflicts, and re-test it. Will update the PR once we have it working. Thanks!

**Pull request closed without merging**
