### PR TITLE
DO NOT MERGE Test what happens without this entry

### PR DESCRIPTION
**Pull request by kiall**

### CODE REVIEW

**Comment by kiall** [comment]
@robdaemon Q - What is the host entry used for? I'm wondering if it's necessary?

**Comment by kiall** [comment]
So - I think this passed because the external DNS names used in caasp-kvm are real, and actually resolve. If the name wasn't real, it likely would have failed - I think.

However, putting on masters in /etc/hosts will likely not work well for multi-master HA .. Maybe we need to treat Dex like we do kube-api, and use haproxy + the 127.0.0.1 hosts entry?

**Comment by inercia** [comment]
I've [removed the same entryi n the CNI PR](https://github.com/kubic-project/salt/pull/201/files#diff-09c149f34d38bfe9b8406e474e155f54) and confirmane tests are passing. So I guess nobody really tries to resolve that name internally. Otherwise, I think things would be really broken, as the _external fqdn_ does not necessarily make sense in the internal network (it was introduced for being used in the `kubeconfig` provided to users and in the certificates).

**Comment by robdaemon** [comment]
This entry is required so that Kubernetes API server can reach the OIDC issuer at all times. It cannot be removed. That's why I added it.

**Comment by robdaemon** [comment]
This entry is required so that Kubernetes API server can reach the OIDC issuer at all times. It cannot be removed. That's why I added it.

**Comment by kiall** [comment]
@robdaemon so - as is - I believe that if the first master fails, dex will be unreachable. We'll need to at the least move this over to use the 127.0.0.1 + haproxy pattern, and possibly use the internal names rather than external endpoint - we should avoid "hijacking" that name if at all possible.

**Comment by robdaemon** [comment]
You can't use the internal name as the issuer must match what the client uses. 127.0.0.1 is going to cause certificate issues. We may be able to do something with haproxy though.

**Pull request closed without merging**
