### PR TITLE
Flake8 cleanup backport 3.0

### PR DESCRIPTION
**Pull request by dannysauer**
Backport PRs #567 and #703 to fix flake8 code formatting warnings.

Is a Bugzilla entry required for simple things like this?  Tagging no-ref for now.

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
adding Florian as a reviewer since he was in the initial PR

**Comment by jordimassaguerpla** [comment]
Sorry I am not familiar with this code to review it myself.

**Comment by hwoarang** [comment]
Looks like we need https://github.com/kubic-project/salt/pull/706 for flake8 tests to pass on release-3.0

**Comment by dannysauer** [comment]
...rebased to include now-merged #706

**Comment by jordimassaguerpla** [comment]
@dannysauer About the bug... Why do we need to release this to our customers?

**Comment by jordimassaguerpla** [comment]
I don't think we are updating to python3 in the 3.0 branch. I am closing  it. Feel free to reopen if you need this to fix a bug.

**Pull request closed without merging**
